### ISSUE TITLE
CasparCG Server is not built under windows 10 home x64 with  MSVC 15.9.51 neither under debugging nor in release

### ISSUE THREAD

**Issue by RomanED** [CasparCG/server#1453]
Compiler MSVC 15.9.51 (MSVS 2017 Enterprise)

1. first of all, I don't quite understand from the build documentation what dependencies I need to build a project for debugging and release for a particular platform
2. The number of steps in the documentation clearly indicates that in the "build" section compilation should be done out of the box without problems?

if I build in release for example, I have the following errors:
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(stream_reader_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(media_route_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(media_sink_device_info_callback_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(read_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(menu_model_delegate_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(cookie_access_filter_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(response_filter_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(x509cert_principal_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(media_sink_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(media_source_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(v8stack_frame_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(post_data_element_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(delete_cookies_callback_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(set_cookie_callback_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(media_observer_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(media_route_create_callback_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(x509certificate_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(write_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(get_extension_resource_callback_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(cookie_visitor_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(accessibility_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(resource_request_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(select_client_certificate_callback_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(sslinfo_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(media_access_callback_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(print_dialog_callback_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(print_job_callback_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(print_settings_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(before_download_callback_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(download_item_callback_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(download_item_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(jsdialog_callback_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(context_menu_params_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(menu_model_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(run_context_menu_callback_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(file_dialog_callback_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(response_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(post_data_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(domdocument_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(auth_callback_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(v8stack_trace_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(callback_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(resource_read_callback_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(resource_skip_callback_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(resolve_callback_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(cookie_manager_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(media_router_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(domnode_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(stream_writer_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(extension_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(sslstatus_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(request_context_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(print_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(render_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(request_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(image_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(keyboard_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(life_span_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(load_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(media_access_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(find_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(focus_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(frame_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(jsdialog_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(dialog_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(display_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(download_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(drag_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(urlrequest_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(task_runner_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(audio_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(context_menu_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(web_plugin_info_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(domvisitor_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(string_visitor_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(urlrequest_client_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(resource_bundle_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(scheme_registrar_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(resource_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(request_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(registration_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(request_context_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(browser_process_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(render_process_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(dictionary_value_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(drag_data_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(extension_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(navigation_entry_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(navigation_entry_visitor_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(pdf_print_callback_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(run_file_dialog_callback_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(browser_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(v8exception_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(client_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(dev_tools_message_observer_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(download_image_callback_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(v8accessor_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(v8array_buffer_release_callback_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(v8interceptor_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(v8context_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(frame_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(value_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(transfer_util.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(base_ref_counted_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(web_plugin_info_visitor_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(web_plugin_unstable_callback_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(binary_value_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(command_line_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(end_tracing_callback_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(scheme_handler_factory_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(task_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(v8handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(browser_host_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(list_value_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(app_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(completion_callback_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(cef_logging.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(process_message_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(libcef_dll_wrapper.obj)	1	
Error	LNK2001	unresolved external symbol __CxxFrameHandler4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(v8value_ctocpp.obj)	1	
Error	LNK2001	unresolved external symbol __GSHandlerCheck_EH4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(cookie_visitor_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __GSHandlerCheck_EH4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(cookie_access_filter_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __GSHandlerCheck_EH4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(keyboard_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __GSHandlerCheck_EH4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(life_span_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __GSHandlerCheck_EH4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(render_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __GSHandlerCheck_EH4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(extension_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __GSHandlerCheck_EH4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(cef_logging.obj)	1	
Error	LNK2001	unresolved external symbol __GSHandlerCheck_EH4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(audio_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __GSHandlerCheck_EH4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(drag_handler_cpptoc.obj)	1	
Error	LNK2001	unresolved external symbol __GSHandlerCheck_EH4	casparcg	C:\repos\casparCG\casparcg-server\build\shell\libcef_dll_wrapper.lib(find_handler_cpptoc.obj)	1	

the same errors will be in debug...

**Comment by Julusian** [comment]
I appear to have forgotten to update some documentation, as 2019 is now required to build this

**Comment by RomanED** [comment]
Ok, and what about Client? Build with Qt 5.14.2 with MingW or MSVC, what versions? What version Qt, MSVC need for Client project?

**Comment by RomanED** [comment]
> I appear to have forgotten to update some documentation, as 2019 is now required to build this

Ok, and what about Client? Build with Qt 5.14.2 with MingW or MSVC, what versions? What version Qt, MSVC need for Client project?

**Comment by Julusian** [comment]
I don't know about the client, I haven't tried to build that myself for many many years. I expect that whatever is documented in the readme is accurate

**Comment by RomanED** [comment]
Somebody knows about how to build caspar client? I tried build CasparCG client with MingW 7.3.0 x64 , add executable and builded libs in deploy directory, and every time I get a runtime error "The entry point <..name_entry> to the procedure was not found"
