### ISSUE TITLE
Build on Ubuntu 18.04 broken?

### ISSUE THREAD

**Issue by saltomodules** [CasparCG/server#1258]
While trying to build (currently the latest) commit 61971eb4 with `./tools/linux/build-in-docker` it fails, first with an error on a missing ffmpeg 4.2.2:

```
Sending build context to Docker daemon  4.195MB
Step 1/29 : ARG IMAGE_BASE
Step 2/29 : ARG IMAGE_BOOST
Step 3/29 : ARG IMAGE_FFMPEG
Step 4/29 : ARG IMAGE_CEF
Step 5/29 : FROM ${IMAGE_BOOST} as boost
 ---> 4a66fb363e14
Step 6/29 : FROM ${IMAGE_FFMPEG} as ffmpeg
manifest for casparcg/ffmpeg:4.2.2 not found
```
Running `./build-base-images ` seems to fix this. 

However, building now fails later on in CasparCG's main build sequence with a `no matching function for call to 'max(int64_t, long long int)'` error on `ffmpeg_producer.cpp.o`:

```
[ 64%] Building CXX object modules/ffmpeg/CMakeFiles/ffmpeg.dir/producer/ffmpeg_producer.cpp.o
/source/modules/ffmpeg/producer/ffmpeg_producer.cpp: In member function 'virtual std::__cxx11::wstring caspar::ffmpeg::ffmpeg_producer::print() const':
/source/modules/ffmpeg/producer/ffmpeg_producer.cpp:185:83: error: no matching function for call to 'max(int64_t, long long int)'
         const auto position = std::max(producer_->time() - producer_->start(), 0ll);
                                                                                   ^
In file included from /usr/include/c++/7/algorithm:61:0,
                 from /build/modules/ffmpeg/ffmpeg_pch/StdAfx.h:22:
/usr/include/c++/7/bits/stl_algobase.h:219:5: note: candidate: template<class _Tp> constexpr const _Tp& std::max(const _Tp&, const _Tp&)
     max(const _Tp& __a, const _Tp& __b)
     ^~~
/usr/include/c++/7/bits/stl_algobase.h:219:5: note:   template argument deduction/substitution failed:
/source/modules/ffmpeg/producer/ffmpeg_producer.cpp:185:83: note:   deduced conflicting types for parameter 'const _Tp' ('long int' and 'long long int')
         const auto position = std::max(producer_->time() - producer_->start(), 0ll);
                                                                                   ^
In file included from /usr/include/c++/7/algorithm:61:0,
                 from /build/modules/ffmpeg/ffmpeg_pch/StdAfx.h:22:
/usr/include/c++/7/bits/stl_algobase.h:265:5: note: candidate: template<class _Tp, class _Compare> constexpr const _Tp& std::max(const _Tp&, const _Tp&, _Compare)
     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^~~
/usr/include/c++/7/bits/stl_algobase.h:265:5: note:   template argument deduction/substitution failed:
/source/modules/ffmpeg/producer/ffmpeg_producer.cpp:185:83: note:   deduced conflicting types for parameter 'const _Tp' ('long int' and 'long long int')
         const auto position = std::max(producer_->time() - producer_->start(), 0ll);
                                                                                   ^
In file included from /usr/include/c++/7/algorithm:62:0,
                 from /build/modules/ffmpeg/ffmpeg_pch/StdAfx.h:22:
/usr/include/c++/7/bits/stl_algo.h:3462:5: note: candidate: template<class _Tp> constexpr _Tp std::max(std::initializer_list<_Tp>)
     max(initializer_list<_Tp> __l)
     ^~~
/usr/include/c++/7/bits/stl_algo.h:3462:5: note:   template argument deduction/substitution failed:
/source/modules/ffmpeg/producer/ffmpeg_producer.cpp:185:83: note:   mismatched types 'std::initializer_list<_Tp>' and 'long int'
         const auto position = std::max(producer_->time() - producer_->start(), 0ll);
                                                                                   ^
In file included from /usr/include/c++/7/algorithm:62:0,
                 from /build/modules/ffmpeg/ffmpeg_pch/StdAfx.h:22:
/usr/include/c++/7/bits/stl_algo.h:3468:5: note: candidate: template<class _Tp, class _Compare> constexpr _Tp std::max(std::initializer_list<_Tp>, _Compare)
     max(initializer_list<_Tp> __l, _Compare __comp)
     ^~~
/usr/include/c++/7/bits/stl_algo.h:3468:5: note:   template argument deduction/substitution failed:
/source/modules/ffmpeg/producer/ffmpeg_producer.cpp:185:83: note:   mismatched types 'std::initializer_list<_Tp>' and 'long int'
         const auto position = std::max(producer_->time() - producer_->start(), 0ll);
                                                                                   ^
[ 65%] Building CXX object modules/ffmpeg/CMakeFiles/ffmpeg.dir/consumer/ffmpeg_consumer.cpp.o
modules/ffmpeg/CMakeFiles/ffmpeg.dir/build.make:151: recipe for target 'modules/ffmpeg/CMakeFiles/ffmpeg.dir/producer/ffmpeg_producer.cpp.o' failed
```

Any idea how to fix this?

**Comment by Julusian** [comment]
In ffmpeg_producer.cpp try changing line 185 to const `auto position = std::max(producer_->time() - producer_->start(), INT64_C(0));`
I shall try and get this fixed in master today, once I have checked that line works on windows

**Comment by saltomodules** [comment]
Can confirm this fixes the build on Ubuntu. Thanks!

**Comment by Julusian** [comment]
Fix pushed
