### ISSUE TITLE
Ubuntu 22.04 compilation issue

### ISSUE THREAD

**Issue by krzyc** [CasparCG/server#1434]
### Expected behaviour
Following build instructions should produce executable.

### Current behaviour
After succesful compilation there is linking issue with tokenize_args recently introduced in commit c4e5e488b9e4e8a0783920448ba139558450997a in src/core/producer/transition/sting_producer.cpp:

```
/usr/bin/ld: ../core/libcore.a(sting_producer.cpp.o): in function `caspar::core::try_match_sting(std::vector<std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, std::allocator<std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > > > const&, caspar::core::sting_info&)':
sting_producer.cpp:(.text+0xfab): undefined reference to `caspar::protocol::amcp::tokenize_args(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [shell/CMakeFiles/casparcg.dir/build.make:173: shell/casparcg] Błąd 1
make[1]: *** [CMakeFiles/Makefile2:668: shell/CMakeFiles/casparcg.dir/all] Błąd 2
make: *** [Makefile:91: all] Błąd 2
```

### Environment
* Commit: 16ee0e3df5c2a0bebe80c9019e19255ac52c6418
* Operating system: Kubuntu 22.04
* GCC 11.2.0

**Comment by poldon** [comment]
This also happens on Ubuntu 20.04.  It appears to be caused by commit c4e5e488b9e4e8a0783920448ba139558450997a.

**Comment by Julusian** [comment]
please try latest master, it should be fixed now

**Comment by krzyc** [comment]
Works for me, thanks.
